### ISSUE TITLE
Cannot find STORE> in manual

### ISSUE THREAD

**Issue by fuadlabgit** [andrea-luciani/bimets#5]
Problem description:
I found an R code using

COMMENT> ...
BEHAVIORAL> ...
TSRANGE ...
EQ >
COEFF>
**STORE > coe(3)** 

however, I did not find this STORE command anywhere in the documentation, unfortunately.
I am R beginner so maybe I am just confused by something that is no issue for experienced developers...

Potential solution: simply add it in the description vignette document.

**Comment by andrea-luciani** [comment]
Hi @fuadlabgit 

`STORE>` MDL keyword had a meaning in an old Fortran econometric code, but today it has no meaning in `bimets`. Its presence does not issue an error in R, so it is not required to be removed from the dated Fortran models when migrated to R.

You can simply delete that line of MDL code or ignore it.

`bimets `documentation do not refer to `STORE `because, as said, it has no meaning in R.

**Comment by fuadlabgit** [comment]
Thanks for the hint @andrea-luciani ! I guess this can be considered as closed then...
