### ISSUE TITLE
LOG and EXP tranformations or with TABIT

### ISSUE THREAD

**Issue by rrremedio** [andrea-luciani/bimets#7]
Hi, @andrea-luciani 

Thank you for replying the question about the output.
If this is not the appropriate forum for these kind of questions, I am open to moving it to the correct place.

I can use TS functions, like this fashion TSLAG(1 + some var). However, it's not possible to make this transformation using the LOG function, or even use it along with TABIT. That is, LOG(1 + some var) inside a model or TABIT(LOG(some var)), returns an error. The same occurs with the EXP function.

Those would be interisting features.

**Comment by andrea-luciani** [comment]
Hi @rrremedio 

Feel free to ask here anything you want to know about the package.

`LOG(ts)` and `EXP(ts)` - uppercase names - are MDL functions: users can use these functions only in MDL model definition. See pag. 105 of the Ref. Manual https://cran.r-project.org/web/packages/bimets/bimets.pdf

In MDL syntax, we introduced the uppercase functions because the list of allowed MDL functions is restricted: syntax and semantic checks must control what users code in their model definition, so we had to allow an MDL equivalent of the base `log` and `exp` functions, i.e. the uppercase `LOG` and `EXP`.


In all other cases, users can simply use the base R function `log(ts)` and `exp(ts)`.

An example follows:
```
> ts=TSERIES(1:10,START=c(2000,1),FREQ=4)
> TABIT(log(1+ts))

      Date, Prd., log(1 + ts)    

   2000 Q1, 1   ,  0.6931472     
   2000 Q2, 2   ,  1.098612      
   2000 Q3, 3   ,  1.386294      
   2000 Q4, 4   ,  1.609438      
   2001 Q1, 1   ,  1.791759      
   2001 Q2, 2   ,  1.94591       
   2001 Q3, 3   ,  2.079442      
   2001 Q4, 4   ,  2.197225      
   2002 Q1, 1   ,  2.302585      
   2002 Q2, 2   ,  2.397895      

```    

Example of MDL with `LOG`:

```
COMMENT> Consumption
BEHAVIORAL> cn
TSRANGE 1921 1 1941 1
EQ> cn =  a1 + a2*p + a3*TSLAG(p,1) + a4*LOG(w1+w2) 
COEFF> a1 a2 a3 a4
RESTRICT> a1+a1=1
```
